<?php
require_once 'shared/header.php';
?>

<main class="flex-shrink-0">
    <div class="container py-5 px-5 mt-5">
        <h2 class="border-1 border-bottom border-dark">The Code for Helt I Hundre.</h2>
        <div class="row row-cols-1 row-cols-lg-2">
            <div class="col-lg-8">
                <pre class="line-numbers"><code class="language-javascript">
                //Start/controller function
                function getValues() {
                    let startValue = document.querySelector('#startValue').value;
                    let endValue = document.querySelector('#endValue').value;

                    //Validate input
                    startValue = parseInt(startValue);
                    endValue = parseInt(endValue);

                    if (Number.isInteger(startValue) && Number.isInteger(endValue)) {
                        let numbersArray = generateNumbers(startValue, endValue);
                        displayNumbers(numbersArray);
                    } else {
                        alert('Only integers are valid!');
                    }

                }

                //Logic function
                function generateNumbers(start, end) {
                    let numbers = [];

                    for (let index = start; index <= end; index++) {
                        numbers.push(index);
                    }

                    return numbers;
                }

                //Display/view function
                function displayNumbers(numbers) {
                    let templateRows = "";
                    let className;

                    for (let i = 0; i < numbers.length; i++) {
                        let number = numbers[i];

                        if (number % 2 == 0) {
                            className = "even";
                        } else {
                            className = "odd"
                        }
                        //This does not render correctly in Prism. See source code on GitHub
                        templateRows += `<tr><td class="${className}">${number}</td></tr>`;
                    }

                    document.querySelector('#results').innerHTML = templateRows;
                }
                </code>
                </pre>
            </div>
            <div class="col-lg-4">
                <p>The code is structed in three functions. One function to start or control the app, one for logic and one to display the results.</p>
                <h5>Get Values</h5>
                <p>getValues is a start/controller function that will fetch the number values from the UI, validate them, pass them on to the logic functionality and eventually call the display/view function</p>
                <h5>Generate Numbers</h5>
                <p>generateNumbers is a logic function that will generate numbers between the start value and the end value. The generated numbers are then pushed into an array which is returned to the controller function (getValues).</p>
                <h5>Display Numbers</h5>
                <p>displayNumbers is a display/view function which will take in the array of numbers generated by the logic function and arrange them in an HTML template to be displayed as results in the UI. This is done by running the numbers array through a for loop where the numbers are sorted in odds and evens, and given a class name used for differentiate the styling between them.</p>
            </div>
        </div>
    </div>
</main>
<script src="js/prism.js"></script>
<script>
    Prism.plugins.NormalizeWhitespace.setDefaults({
        'remove-trailing': true,
        'remove-indent': true,
        'left-trim': true,
        'right-trim': true
    })
</script>
<?php
require_once 'shared/footer.php';
?>